<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 *Currency Declarative Type
 */
class Denomination implements JsonSerializable
{
    /**
     * Available Name: KE
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Amount to Request
     * @required
     * @var integer $value public property
     */
    public $value;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name  Initialization value for $this->name
     * @param integer $value Initialization value for $this->value
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->name = func_get_arg(0);
                $this->value = func_get_arg(1);
                break;

            default:
                $this->name = 'KE';
                $this->value = 10;
                break;
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name'] = $this->name;
        $json['value'] = $this->value;

        return $json;
    }
}
