<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PartnerAirtimeRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var \Noorfarooqy\Credofaster\Models\Initiator $initiator public property
     */
    public $initiator;

    /**
     * @todo Write general description for this property
     * @required
     * @var \Noorfarooqy\Credofaster\Models\SingleAirtimeParameter[] $parameters public property
     */
    public $parameters;

    /**
     * Constructor to set initial or default values of member properties
     * @param Initiator $initiator  Initialization value for $this->initiator
     * @param array     $parameters Initialization value for $this->parameters
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->initiator = func_get_arg(0);
            $this->parameters = func_get_arg(1);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['initiator'] = $this->initiator;
        $json['parameters'] = $this->parameters;

        return $json;
    }
}
