<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 *Balance Response
 */
class PartnerAirtimeBalanceResponse implements JsonSerializable
{
    /**
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     * @required
     * @maps ErrorCode
     * @var integer $errorCode public property
     */
    public $errorCode;

    /**
     * Text Description
     * @required
     * @maps ErrorDescription
     * @var string $errorDescription public property
     */
    public $errorDescription;

    /**
     * Remaining Tentative Balance
     * @required
     * @maps UnitBalance
     * @var integer $unitBalance public property
     */
    public $unitBalance;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $errorCode        Initialization value for $this->errorCode
     * @param string  $errorDescription Initialization value for $this->errorDescription
     * @param integer $unitBalance      Initialization value for $this->unitBalance
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 3:
                $this->errorCode = func_get_arg(0);
                $this->errorDescription = func_get_arg(1);
                $this->unitBalance = func_get_arg(2);
                break;

            default:
                $this->errorCode = 0;
                $this->errorDescription = 'Success.';
                $this->unitBalance = 0;
                break;
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ErrorCode'] = $this->errorCode;
        $json['ErrorDescription'] = $this->errorDescription;
        $json['UnitBalance'] = $this->unitBalance;

        return $json;
    }
}
