<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 *Response you get for A Request
 */
class PartnerAirtimeResponse implements JsonSerializable
{
    /**
     * Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
     * @required
     * @maps ErrorCode
     * @var integer $errorCode public property
     */
    public $errorCode;

    /**
     * Text Description
     * @required
     * @maps ErrorDescription
     * @var string $errorDescription public property
     */
    public $errorDescription;

    /**
     * a UUID Returned for the Transaction
     * @required
     * @maps ReferenceId
     * @var string $referenceId public property
     */
    public $referenceId;

    /**
     * Return of the Clients Request ID
     * @required
     * @maps RequestId
     * @var string $requestId public property
     */
    public $requestId;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $errorCode        Initialization value for $this->errorCode
     * @param string  $errorDescription Initialization value for $this->errorDescription
     * @param string  $referenceId      Initialization value for $this->referenceId
     * @param string  $requestId        Initialization value for $this->requestId
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 4:
                $this->errorCode = func_get_arg(0);
                $this->errorDescription = func_get_arg(1);
                $this->referenceId = func_get_arg(2);
                $this->requestId = func_get_arg(3);
                break;

            default:
                $this->errorCode = 0;
                break;
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ErrorCode'] = $this->errorCode;
        $json['ErrorDescription'] = $this->errorDescription;
        $json['ReferenceId'] = $this->referenceId;
        $json['RequestId'] = $this->requestId;

        return $json;
    }
}
