<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class RegisterCallbackResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps ErrorCode
     * @var integer $errorCode public property
     */
    public $errorCode;

    /**
     * @todo Write general description for this property
     * @required
     * @maps ErrorDescription
     * @var string $errorDescription public property
     */
    public $errorDescription;

    /**
     * @todo Write general description for this property
     * @required
     * @maps RegisteredCallbackUrl
     * @var string $registeredCallbackUrl public property
     */
    public $registeredCallbackUrl;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $errorCode             Initialization value for $this->errorCode
     * @param string  $errorDescription      Initialization value for $this->errorDescription
     * @param string  $registeredCallbackUrl Initialization value for $this->registeredCallbackUrl
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->errorCode = func_get_arg(0);
            $this->errorDescription = func_get_arg(1);
            $this->registeredCallbackUrl = func_get_arg(2);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ErrorCode'] = $this->errorCode;
        $json['ErrorDescription'] = $this->errorDescription;
        $json['RegisteredCallbackUrl'] = $this->registeredCallbackUrl;

        return $json;
    }
}
