<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SingleAirtimeParameter implements JsonSerializable
{
    /**
     * A UUID for Each
     * @required
     * @maps reference_id
     * @var string $referenceId public property
     */
    public $referenceId;

    /**
     * Which Country are you requesting in
     * @required
     * @var string $country public property
     */
    public $country;

    /**
     * The Receipient's Account. Can be Phone Number(International Format)
     * @required
     * @maps account_no
     * @var string $accountNo public property
     */
    public $accountNo;

    /**
     * Currency Declarative Type
     * @required
     * @var \Noorfarooqy\Credofaster\Models\Denomination $denomination public property
     */
    public $denomination;

    /**
     * Any Other Tags to accompany the Request
     * @required
     * @var object $other public property
     */
    public $other;

    /**
     * Constructor to set initial or default values of member properties
     * @param string       $referenceId  Initialization value for $this->referenceId
     * @param string       $country      Initialization value for $this->country
     * @param string       $accountNo    Initialization value for $this->accountNo
     * @param Denomination $denomination Initialization value for $this->denomination
     * @param object       $other        Initialization value for $this->other
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 5:
                $this->referenceId = func_get_arg(0);
                $this->country = func_get_arg(1);
                $this->accountNo = func_get_arg(2);
                $this->denomination = func_get_arg(3);
                $this->other = func_get_arg(4);
                break;

            default:
                $this->country = 'KE';
                $this->accountNo = '254705126329';
                break;
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['reference_id'] = $this->referenceId;
        $json['country'] = $this->country;
        $json['account_no'] = $this->accountNo;
        $json['denomination'] = $this->denomination;
        $json['other'] = $this->other;

        return $json;
    }
}
