<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The environment being used'
     * @var string
     */
    public static $environment = Environments::SANDBOX;

    /**
     * Assigned APIKey
     * @var string
     */
    public static $apiKey = 'XXXX-XXXX-XXXX-XXXX';

    /**
     * Assigned ClientId
     * @var string
     */
    public static $clientId = 'ABCDEDFG1234';

    /**
     * Get the base uri for a given server in the current environment
     * @param  string $server Server name
     * @return string         Base URI
     */
    public static function getBaseUri($server = Servers::DEFAULT_)
    {
        return APIHelper::appendUrlWithTemplateParameters(
            static::$environmentsMap[static::$environment][$server],
            array(
            )
        );
    }

    /**
     * A map of all baseurls used in different environments and servers
     * @var array
     */
    private static $environmentsMap = array(
        Environments::PRODUCTION => array(
            Servers::DEFAULT_ => 'https://api.partner.credofaster.co.ke',
            Servers::MY_CALLBACK_ENDPOINT => 'https://posthere.io/dfd0-4d32-8ad9',
        ),
        Environments::SANDBOX => array(
            Servers::DEFAULT_ => 'https://api-test.partner.credofaster.co.ke',
            Servers::MY_CALLBACK_ENDPOINT => 'https://posthere.io/dfd0-4d32-8ad9',
        ),
    );
}
