<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster;

use Noorfarooqy\Credofaster\Controllers;

/**
 * CredofasterSDK client class
 */
class CredofasterPartnerApiClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $apiKey = null,
        $clientId = null
    ) {
        Configuration::$apiKey = $apiKey ? $apiKey : Configuration::$apiKey;
        Configuration::$clientId = $clientId ? $clientId : Configuration::$clientId;
    }
    /**
     * Singleton access to Main controller
     * @return Controllers\MainController The *Singleton* instance
     */
    public function getMain()
    {
        return Controllers\MainController::getInstance();
    }
    /**
     * Singleton access to Events controller
     * @return Controllers\EventsController The *Singleton* instance
     */
    public function getEvents()
    {
        return Controllers\EventsController::getInstance();
    }
}
