<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * Live Environment
     */
    const PRODUCTION = "production";

    /**
     * For Test Purpose
     */
    const SANDBOX = "Sandbox";
}
