<?php
/*
 * CredofasterSDK
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Noorfarooqy\Credofaster;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const DEFAULT_ = "default";

    /**
     * TODO: Write general description for this element
     */
    const MY_CALLBACK_ENDPOINT = "MY_CALLBACK_ENDPOINT";
}
